name: Deploy Workflow to test concurrency

on:
  push:
    branches:
           - 'main'
    paths-ignore:
      - '**/README.md'       
  pull_request:
        branches:
              - 'main'
        paths-ignore:
              - '**/README.md'          

jobs:
  build:
    uses: aaditya-20/GithubActionDemo/.github/workflows/FirstOne.yml@main
    
  build2:
    uses: aaditya-20/GithubActionDemo/.github/workflows/SecondFile.yml@main 
    
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more test steps here

  deploy-staging:
  
    needs: [build,build2]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          # Deployment to staging steps
          
          echo "Deploying to staging environment"
          sleep 120

  # deploy-production:
  #  needs: [build]
  #  runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Deploy to Production
  #       run: |
  #         # Deployment to production steps
  #         echo "Deploying to production environment"
  #         sleep 120
